Tganley/feature/ns payloads
AlbertaSat/ex2_obc_software pull request #211
Opened 2022-06-28 22:44 UTC by tganley

Tested on hardware in the flatsat. Only known issue is that the xmodem code will require more work and testing.

2022-06-30 18:01 UTC, rcunrau submitted a review, later dismissed
Great work! :-)

2022-07-01 17:15 UTC, Taylorr82 requested changes

2022-07-01 17:15 UTC, Taylorr82 commented on ex2_hal/northern_spirit/equipment_handler/include/northern_voices_games.h
> +#include <redposix.h>
Headers should only have the bare minimum includes, I don't see any reliance edge stuff in a few of these, headers, should remove them

2022-07-01 17:15 UTC, Taylorr82 commented on ex2_hal/northern_spirit/equipment_handler/include/northern_spirit_io.h
> +#include "FreeRTOS.h"
Lots of unneeded includes here too. Includes not needed by the header but needed in the C file should be only in the C file

2022-07-01 18:04 UTC, tganley commented on source/base_64.c
> +/*
Good call. I'll put the xmodem stuff in there too maybe

2022-07-01 20:15 UTC, Taylorr82 approved these changes

2022-07-01 20:22 UTC, Taylorr82 approved these changes

2022-07-01 20:22 UTC, merged