Jenish/feature/iris-service-obc
AlbertaSat/ex2_obc_software pull request #227
Opened 2022-07-07 18:55 UTC by JenishPatel99

Includes iris service and sub-services definitions on obc side

2022-07-08 16:06 UTC, Taylorr82 requested changes
Your while loops skip the log messages you put in ERROR_STATE and FINISH, we talked about this yesterday too, did you makes changes about that?

2022-07-08 16:06 UTC, Taylorr82 commented on ex2_hal/iris/hardware_interface/source/iris.c
> +            // TODO: Verify Endianness and correct order of storage
This is completed, right?

2022-07-08 23:23 UTC, JenishPatel99 commented on ex2_hal/iris/hardware_interface/source/iris.c
>      while (controller_state != FINISH && controller_state != ERROR_STATE) {
Changes made :+1:

2022-07-08 23:25 UTC, JenishPatel99 commented on ex2_hal/iris/hardware_interface/include/iris.h
> - /**
Should also check all of my files are properly named and commented. Thanks !

2022-07-08 23:25 UTC, JenishPatel99 commented on ex2_hal/iris/hardware_interface/source/iris.c
> +            // TODO: Verify Endianness and correct order of storage
Yes

2022-07-11 17:29 UTC, Taylorr82 approved these changes

2022-07-11 21:03 UTC, merged