Tganley/bugfix/iris fs test plan fixes
AlbertaSat/ex2_obc_software pull request #266
Opened 2022-07-27 19:42 UTC by tganley

2022-07-27 19:46 UTC, tganley commented
This was originally meant to be merged into Jenish's Iris branch. It's all tested on the flatsat.

2022-07-28 19:14 UTC, Taylorr82 requested changes

2022-07-28 19:14 UTC, Taylorr82 commented on ex2_system/source/diagnostic/diagnostic.c
> +                ex2_log("Payload failed to power off.");
sys_log

2022-07-28 20:59 UTC, Taylorr82 commented on ex2_hal/iris/hardware_interface/source/iris.c
>      if (fptr == NULL) {
Doesn't this return -1 on failure?

2022-07-28 22:14 UTC, tganley commented on ex2_hal/iris/hardware_interface/source/iris.c
>      if (fptr == NULL) {
Yes! Bad Jenish

2022-07-28 22:24 UTC, Taylorr82 approved these changes

2022-07-28 22:28 UTC, merged