Update system.h for other users of ex2_obc_software
AlbertaSat/ex2_obc_software pull request #71
Opened 2021-10-29 20:43 UTC by tganley

Fix the previously-unaccounted-for fact that communication protocol numbers do not correspond to MCU register numbers, for instance UART1 is actually sciREG4.

2021-10-30 00:12 UTC, Taylorr82 requested changes

2021-10-30 00:12 UTC, Taylorr82 commented on main/system.h
> +    #define PAYLOAD_SCI sciREG1
having multiple definitions of the same sciREG will cause issues in the interrupt switch() statements. We need to come up with a way to exclude compiling certain things based on the payload installed. Probably similar to IS_ATHENA

2021-10-30 00:12 UTC, Taylorr82 commented on main/system.h
> +    #endif
much more concise than the way I did it

2021-10-30 00:12 UTC, Taylorr82 commented on main/system.h
> +    #define SD_SPI spiREG1          //?
Did you change these knowing they are likely to get all messed up by development? I don't think that's necessarily a bad thing

2021-11-27 23:07 UTC, tganley commented
This pull request is stale and has a lot of commits that were not intended to be merged. The changes to system.h will be carried into master once we're ready to merge everything.

2021-11-27 23:07 UTC, closed without merging